services:
  - type: web
    name: emotional-orchestrator
    env: python
    plan: free
    buildCommand: cd orchestrator && pip install -r requirements.txt
    startCommand: cd orchestrator && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emotional-ai-db
          property: connectionString
      - key: EMOTION_MODULE_URL
        value: https://emotion-module.onrender.com
      - key: PERSONALITY_MODULE_URL
        value: https://personality-module.onrender.com
	pythonVersion: "3.12.3"
  - type: web
    name: emotion-module
    env: python
    plan: free
    buildCommand: cd emotion_module && pip install -r requirements.txt
    startCommand: cd emotion_module && uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: personality-module
    env: python
    plan: free
    buildCommand: cd personality_module && pip install -r requirements.txt
    startCommand: cd personality_module && uvicorn app.main:app --host 0.0.0.0 --port $PORT
